/* Generated By:JavaCC: Do not edit this line. OfuscadorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OfuscadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMA = 1;
  /** RegularExpression Id. */
  int RESTA = 2;
  /** RegularExpression Id. */
  int IGUAL = 3;
  /** RegularExpression Id. */
  int MULTIPLICACION = 4;
  /** RegularExpression Id. */
  int DIVISION = 5;
  /** RegularExpression Id. */
  int MAYOR_QUE = 6;
  /** RegularExpression Id. */
  int MENOR_QUE = 7;
  /** RegularExpression Id. */
  int MODULO = 8;
  /** RegularExpression Id. */
  int EXCLAMACION = 9;
  /** RegularExpression Id. */
  int AMPERSAND = 10;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 11;
  /** RegularExpression Id. */
  int LETRA_MIN = 12;
  /** RegularExpression Id. */
  int PUBLIC = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int STATIC = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int FLOAT = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int SYSTEM = 24;
  /** RegularExpression Id. */
  int STRING = 25;
  /** RegularExpression Id. */
  int ARG = 26;
  /** RegularExpression Id. */
  int INTEGER = 27;
  /** RegularExpression Id. */
  int BOOLEAN = 28;
  /** RegularExpression Id. */
  int TRUE = 29;
  /** RegularExpression Id. */
  int FALSE = 30;
  /** RegularExpression Id. */
  int RETURN = 31;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int NUMERO_INT = 33;
  /** RegularExpression Id. */
  int METODO = 34;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 35;
  /** RegularExpression Id. */
  int LLAVE_DER = 36;
  /** RegularExpression Id. */
  int PARENTESIS_IZQ = 37;
  /** RegularExpression Id. */
  int PARENTESIS_DER = 38;
  /** RegularExpression Id. */
  int CORCHETE_IZQ = 39;
  /** RegularExpression Id. */
  int CORCHETE_DER = 40;
  /** RegularExpression Id. */
  int PUNTO_COMA = 41;
  /** RegularExpression Id. */
  int COMILLAS = 42;
  /** RegularExpression Id. */
  int COMENTARIO = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"%\"",
    "\"!\"",
    "\"&\"",
    "\":\"",
    "<LETRA_MIN>",
    "\"public\"",
    "\"class\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"int\"",
    "\"float\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"System\"",
    "\"String\"",
    "\"arg\"",
    "\"Integer\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "<ID>",
    "<NUMERO_INT>",
    "<METODO>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"\\\"\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMENTARIO>",
    "<token of kind 48>",
  };

}
