/* Generated By:JavaCC: Do not edit this line. ProyectoPT2Constants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProyectoPT2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CORCHETE_IZQ = 1;
  /** RegularExpression Id. */
  int CORCHETE_DER = 2;
  /** RegularExpression Id. */
  int PARENTESIS_IZQ = 3;
  /** RegularExpression Id. */
  int PARENTESIS_DER = 4;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 5;
  /** RegularExpression Id. */
  int LLAVE_DER = 6;
  /** RegularExpression Id. */
  int COMA = 7;
  /** RegularExpression Id. */
  int PUNTO_COMA = 8;
  /** RegularExpression Id. */
  int IGUAL = 9;
  /** RegularExpression Id. */
  int SUMA = 10;
  /** RegularExpression Id. */
  int RESTA = 11;
  /** RegularExpression Id. */
  int MULTIPLICACION = 12;
  /** RegularExpression Id. */
  int DIVISION = 13;
  /** RegularExpression Id. */
  int MODULO = 14;
  /** RegularExpression Id. */
  int MENOR_QUE = 15;
  /** RegularExpression Id. */
  int MAYOR_QUE = 16;
  /** RegularExpression Id. */
  int MENOR_IGUAL_QUE = 17;
  /** RegularExpression Id. */
  int MAYOR_IGUAL_QUE = 18;
  /** RegularExpression Id. */
  int IGUAL_IGUAL = 19;
  /** RegularExpression Id. */
  int DISTINTO = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int EXCLAMACION = 23;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 24;
  /** RegularExpression Id. */
  int COMILLAS = 25;
  /** RegularExpression Id. */
  int PUBLIC = 26;
  /** RegularExpression Id. */
  int CLASS = 27;
  /** RegularExpression Id. */
  int STATIC = 28;
  /** RegularExpression Id. */
  int VOID = 29;
  /** RegularExpression Id. */
  int INT = 30;
  /** RegularExpression Id. */
  int FLOAT = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int FOR = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int SYSTEM = 36;
  /** RegularExpression Id. */
  int STRING = 37;
  /** RegularExpression Id. */
  int ARG = 38;
  /** RegularExpression Id. */
  int INTEGER = 39;
  /** RegularExpression Id. */
  int BOOL = 40;
  /** RegularExpression Id. */
  int BOOLEAN = 41;
  /** RegularExpression Id. */
  int TRUE = 42;
  /** RegularExpression Id. */
  int FALSE = 43;
  /** RegularExpression Id. */
  int RETURN = 44;
  /** RegularExpression Id. */
  int DEF = 45;
  /** RegularExpression Id. */
  int BREAK = 46;
  /** RegularExpression Id. */
  int CONTINUE = 47;
  /** RegularExpression Id. */
  int PRINT = 48;
  /** RegularExpression Id. */
  int ID = 49;
  /** RegularExpression Id. */
  int NUMERO_FLOAT = 50;
  /** RegularExpression Id. */
  int NUMERO_INT = 51;
  /** RegularExpression Id. */
  int NUMERO_HEX = 52;
  /** RegularExpression Id. */
  int CADENA = 53;
  /** RegularExpression Id. */
  int NUMERO_HEX_NT = 54;
  /** RegularExpression Id. */
  int ID_NT = 55;
  /** RegularExpression Id. */
  int ID_NT2 = 56;
  /** RegularExpression Id. */
  int NUMERO_FLOAT_NT1 = 57;
  /** RegularExpression Id. */
  int NUMERO_FLOAT_NT2 = 58;
  /** RegularExpression Id. */
  int COMENTARIO = 63;
  /** RegularExpression Id. */
  int COMENTARIO_VARIASLINEAS = 65;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\":\"",
    "\"\\\"\"",
    "\"public\"",
    "\"class\"",
    "\"static\"",
    "\"void\"",
    "\"int\"",
    "\"float\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"System\"",
    "\"string\"",
    "\"arg\"",
    "\"Integer\"",
    "\"bool\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "\"def\"",
    "\"break\"",
    "\"continue\"",
    "\"print\"",
    "<ID>",
    "<NUMERO_FLOAT>",
    "<NUMERO_INT>",
    "<NUMERO_HEX>",
    "<CADENA>",
    "<NUMERO_HEX_NT>",
    "<ID_NT>",
    "<ID_NT2>",
    "<NUMERO_FLOAT_NT1>",
    "<NUMERO_FLOAT_NT2>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMENTARIO>",
    "<token of kind 64>",
    "<COMENTARIO_VARIASLINEAS>",
  };

}
