/* Generated By:JavaCC: Do not edit this line. Ejercicio1Constants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Ejercicio1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPSUMA = 1;
  /** RegularExpression Id. */
  int LETRAMIN = 2;
  /** RegularExpression Id. */
  int ID = 3;
  /** RegularExpression Id. */
  int MAT = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "<LETRAMIN>",
    "<ID>",
    "<MAT>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 8>",
  };

}
